services:
  qrserver:
    build: .
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: "0.80"
          memory: "512M"
        reservations:
          cpus: "0.25"
          memory: "128M"
